### ISSUE TITLE
CL_DEVICE_NOT_FOUND

### ISSUE THREAD

**Issue by JamesYen220** [SamGinzburg/VectorVisor#6]
Running 
```
cd examples/
cargo run --release -- -i arithmetic/factorial.wat --printreturn=true
```
gives the following errors
```
     Running `/home/user/Code/VectorVisor/target/release/vectorvisor -i binops/sub.wat --printreturn=true`
[src/main.rs:364] matches.clone() = ArgMatches {
    args: {
        "hcallsize": MatchedArg {
            occurs: 0,
            indices: [
                30,
            ],
            vals: [
                "16384",
            ],
        },
        "pinput": MatchedArg {
            occurs: 0,
            indices: [
                37,
            ],
            vals: [
                "true",
            ],
        },
        "mexec": MatchedArg {
            occurs: 0,
            indices: [
                36,
            ],
            vals: [
                "1",
            ],
        },
        "patch": MatchedArg {
            occurs: 0,
            indices: [
                12,
            ],
            vals: [
                "false",
            ],
        },
        "serverless": MatchedArg {
            occurs: 0,
            indices: [
                27,
            ],
            vals: [
                "false",
            ],
        },
        "printreturn": MatchedArg {
            occurs: 1,
            indices: [
                4,
            ],
            vals: [
                "true",
            ],
        },
        "vmgroups": MatchedArg {
            occurs: 0,
            indices: [
                8,
            ],
            vals: [
                "1",
            ],
        },
        "globals-buffer-size": MatchedArg {
            occurs: 0,
            indices: [
                20,
            ],
            vals: [
                "",
            ],
        },
        "forceinline": MatchedArg {
            occurs: 0,
            indices: [
                25,
            ],
            vals: [
                "false",
            ],
        },
        "maxdup": MatchedArg {
            occurs: 0,
            indices: [
                33,
            ],
            vals: [
                "1",
            ],
        },
        "ip": MatchedArg {
            occurs: 0,
            indices: [
                28,
            ],
            vals: [
                "127.0.0.1",
            ],
        },
        "disablefastcalls": MatchedArg {
            occurs: 0,
            indices: [
                34,
            ],
            vals: [
                "false",
            ],
        },
        "localworkgroup": MatchedArg {
            occurs: 0,
            indices: [
                35,
            ],
            vals: [
                "999999",
            ],
        },
        "input": MatchedArg {
            occurs: 1,
            indices: [
                2,
            ],
            vals: [
                "binops/sub.wat",
            ],
        },
        "cflags": MatchedArg {
            occurs: 0,
            indices: [
                16,
            ],
            vals: [
                "",
            ],
        },
        "volatile": MatchedArg {
            occurs: 0,
            indices: [
                23,
            ],
            vals: [
                "false",
            ],
        },
        "maxloc": MatchedArg {
            occurs: 0,
            indices: [
                32,
            ],
            vals: [
                "500000",
            ],
        },
        "debugcallprint": MatchedArg {
            occurs: 0,
            indices: [
                15,
            ],
            vals: [
                "false",
            ],
        },
        "isgpu": MatchedArg {
            occurs: 0,
            indices: [
                10,
            ],
            vals: [
                "true",
            ],
        },
        "callstack": MatchedArg {
            occurs: 0,
            indices: [
                14,
            ],
            vals: [
                "1024",
            ],
        },
        "ldflags": MatchedArg {
            occurs: 0,
            indices: [
                17,
            ],
            vals: [
                "",
            ],
        },
        "interleave": MatchedArg {
            occurs: 0,
            indices: [
                9,
            ],
            vals: [
                "1",
            ],
        },
        "jitcache": MatchedArg {
            occurs: 0,
            indices: [
                22,
            ],
            vals: [
                "false",
            ],
        },
        "partition": MatchedArg {
            occurs: 0,
            indices: [
                24,
            ],
            vals: [
                "true",
            ],
        },
        "nvidia": MatchedArg {
            occurs: 0,
            indices: [
                11,
            ],
            vals: [
                "true",
            ],
        },
        "wasmtime": MatchedArg {
            occurs: 0,
            indices: [
                26,
            ],
            vals: [
                "false",
            ],
        },
        "max_smem_demo_space": MatchedArg {
            occurs: 0,
            indices: [
                39,
            ],
            vals: [
                "0",
            ],
        },
        "profile": MatchedArg {
            occurs: 0,
            indices: [
                41,
            ],
            vals: [
                "false",
            ],
        },
        "fastreply": MatchedArg {
            occurs: 0,
            indices: [
                38,
            ],
            vals: [
                "false",
            ],
        },
        "numfuncs": MatchedArg {
            occurs: 0,
            indices: [
                19,
            ],
            vals: [
                "",
            ],
        },
        "heap": MatchedArg {
            occurs: 0,
            indices: [
                6,
            ],
            vals: [
                "1048576",
            ],
        },
        "stack": MatchedArg {
            occurs: 0,
            indices: [
                5,
            ],
            vals: [
                "1048576",
            ],
        },
        "vmcount": MatchedArg {
            occurs: 0,
            indices: [
                7,
            ],
            vals: [
                "64",
            ],
        },
        "unsafewrite": MatchedArg {
            occurs: 0,
            indices: [
                13,
            ],
            vals: [
                "false",
            ],
        },
        "reqtimeout": MatchedArg {
            occurs: 0,
            indices: [
                40,
            ],
            vals: [
                "2000",
            ],
        },
        "entry": MatchedArg {
            occurs: 0,
            indices: [
                18,
            ],
            vals: [
                "",
            ],
        },
        "compile": MatchedArg {
            occurs: 0,
            indices: [
                21,
            ],
            vals: [
                "false",
            ],
        },
        "port": MatchedArg {
            occurs: 0,
            indices: [
                29,
            ],
            vals: [
                "8000",
            ],
        },
        "partitions": MatchedArg {
            occurs: 0,
            indices: [
                31,
            ],
            vals: [
                "100",
            ],
        },
    },
    subcommand: None,
    usage: Some(
        "USAGE:\n    vectorvisor [OPTIONS] --input <>",
    ),
}
[src/main.rs:420] compile_args.clone() = ""
[src/opencl_writer.rs:2499] program_start_mem_pages = 1
[src/opencl_writer.rs:2500] program_start_max_pages = 16
Func func__start cannot be optimized
[src/opencl_writer.rs:3214] &fast_function_set.len() = 1
Compiled: 2 functions
Entry point: 1
Globals buffer: 0
interleave: 1
thread 'main' panicked at src/main.rs:842:85:
called `Result::unwrap()` on an `Err` value: 

################################ OPENCL ERROR ############################### 

Error executing function: clGetDeviceIDs  

Status error code: CL_DEVICE_NOT_FOUND (-1)  

Please visit the following url for more information: 

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clGetDeviceIDs.html#errors  

############################################################################# 

stack backtrace:
   0:     0x60ab8c096b3c - std::backtrace_rs::backtrace::libunwind::trace::h67a838aed1f4d6ec
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x60ab8c096b3c - std::backtrace_rs::backtrace::trace_unsynchronized::h1d1786bb1962baf8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x60ab8c096b3c - std::sys_common::backtrace::_print_fmt::h5a0b1f807a002d23
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x60ab8c096b3c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf84ab6ad0b91784c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x60ab8c0c1bdc - core::fmt::rt::Argument::fmt::h28f463bd1fdabed5
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9
   5:     0x60ab8c0c1bdc - core::fmt::write::ha37c23b175e921b3
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21
   6:     0x60ab8c09385e - std::io::Write::write_fmt::haa1b000741bcbbe1
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/io/mod.rs:1763:15
   7:     0x60ab8c096924 - std::sys_common::backtrace::_print::h1ff1030b04dfb157
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x60ab8c096924 - std::sys_common::backtrace::print::hb982056c6f29541c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x60ab8c097f93 - std::panicking::default_hook::{{closure}}::h11f92f82c62fbd68
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:272:22
  10:     0x60ab8c097cb4 - std::panicking::default_hook::hb8810fe276772c66
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:292:9
  11:     0x60ab8c098515 - std::panicking::rust_panic_with_hook::hd2f0efd2fec86cb0
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:731:13
  12:     0x60ab8c098411 - std::panicking::begin_panic_handler::{{closure}}::h3651b7fc4f61d784
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:609:13
  13:     0x60ab8c097066 - std::sys_common::backtrace::__rust_end_short_backtrace::hbc468e4b98c7ae04
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x60ab8c098162 - rust_begin_unwind
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
  15:     0x60ab8b6f6505 - core::panicking::panic_fmt::h979245e2fdb2fabd
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
  16:     0x60ab8b6f69e3 - core::result::unwrap_failed::h8c4b86241881fbbb
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1652:5
  17:     0x60ab8b8186fb - vectorvisor::main::h75b24b4e6aaf8cfd
  18:     0x60ab8b7e4813 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4c45c397cd46ab21
  19:     0x60ab8b8d7c39 - std::rt::lang_start::{{closure}}::ha2fe3d93a5592b89
  20:     0x60ab8c08e14b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf9057cfaeeb252e2
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:284:13
  21:     0x60ab8c08e14b - std::panicking::try::do_call::h629e203a624883e4
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
  22:     0x60ab8c08e14b - std::panicking::try::h7b61614724d6a4f1
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
  23:     0x60ab8c08e14b - std::panic::catch_unwind::h354ac1c0268491d8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
  24:     0x60ab8c08e14b - std::rt::lang_start_internal::{{closure}}::h919fee3c5ba8f617
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:48
  25:     0x60ab8c08e14b - std::panicking::try::do_call::h54583f67455bff32
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
  26:     0x60ab8c08e14b - std::panicking::try::hb0e12c4e01d39dc2
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
  27:     0x60ab8c08e14b - std::panic::catch_unwind::h367b6339e3ca9a3b
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
  28:     0x60ab8c08e14b - std::rt::lang_start_internal::ha5ce8533eaa0fda8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:20
  29:     0x60ab8b81baf5 - main
  30:     0x7bea23829d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  31:     0x7bea23829e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  32:     0x60ab8b6f6ca5 - _start
  33:                0x0 - <unknown>
```

Currently system information
```
Number of platforms:                             2
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.0 pocl 1.8  Linux, None+Asserts, RELOC, LLVM 11.1.0, SLEEF, DISTRO, POCL_DEBUG
  Platform Name:                                 Portable Computing Language
  Platform Vendor:                               The pocl project
  Platform Extensions:                           cl_khr_icd cl_pocl_content_size
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 3.0 CUDA 12.3.68
  Platform Name:                                 NVIDIA CUDA
  Platform Vendor:                               NVIDIA Corporation
  Platform Extensions:                           cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_device_uuid cl_khr_pci_bus_info cl_khr_external_semaphore cl_khr_external_memory cl_khr_external_semaphore_opaque_fd cl_khr_external_memory_opaque_fd


  Platform Name:                                 Portable Computing Language
Number of devices:                               1
  Device Type:                                   CL_DEVICE_TYPE_CPU
  Vendor ID:                                     8086h
  Max compute units:                             16
  Max work items dimensions:                     3
    Max work items[0]:                           4096
    Max work items[1]:                           4096
    Max work items[2]:                           4096
  Max work group size:                           4096
  Preferred vector width char:                   16
  Preferred vector width short:                  16
  Preferred vector width int:                    8
  Preferred vector width long:                   4
  Preferred vector width float:                  8
  Preferred vector width double:                 4
  Native vector width char:                      16
  Native vector width short:                     16
  Native vector width int:                       8
  Native vector width long:                      4
  Native vector width float:                     8
  Native vector width double:                    4
  Max clock frequency:                           4800Mhz
  Address bits:                                  64
  Max memory allocation:                         8589934592
  Image support:                                 Yes
  Max number of images read arguments:           128
  Max number of images write arguments:          128
  Max image 2D width:                            16384
  Max image 2D height:                           16384
  Max image 3D width:                            2048
  Max image 3D height:                           2048
  Max image 3D depth:                            2048
  Max samplers within kernel:                    16
  Max size of kernel argument:                   1024
  Alignment (bits) of base address:              1024
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     Yes
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               Yes
    Round to +ve and infinity:                   Yes
    IEEE754-2008 fused multiply-add:             Yes
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    16777216
  Global memory size:                            22889979904
  Constant buffer size:                          262144
  Max number of constant args:                   8
  Local memory type:                             Global
  Local memory size:                             262144
  Max pipe arguments:                            16
  Max pipe active reservations:                  1
  Max pipe packet size:                          1024
  Max global variable size:                      0
  Max global variable preferred total size:      0
  Max read/write image args:                     128
  Max on device events:                          1024
  Queue on device max size:                      262144
  Max on device queues:                          1
  Queue on device preferred size:                16384
  SVM capabilities:                              
    Coarse grain buffer:                         Yes
    Fine grain buffer:                           Yes
    Fine grain system:                           No
    Atomics:                                     Yes
  Preferred platform atomic alignment:           0
  Preferred global atomic alignment:             0
  Preferred local atomic alignment:              0
  Kernel Preferred work group size multiple:     8
  Error correction support:                      0
  Unified memory for Host and Device:            1
  Profiling timer resolution:                    1
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:                                
    Execute OpenCL kernels:                      Yes
    Execute native function:                     Yes
  Queue on Host properties:                              
    Out-of-Order:                                Yes
    Profiling :                                  Yes
  Queue on Device properties:                            
    Out-of-Order:                                Yes
    Profiling :                                  Yes
  Platform ID:                                   0x70150b916008
  Name:                                          pthread-Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
  Vendor:                                        GenuineIntel
  Device OpenCL C version:                       OpenCL C 1.2 pocl
  Driver version:                                1.8
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 1.2 pocl HSTR: pthread-x86_64-pc-linux-gnu-skylake
  Extensions:                                    cl_khr_byte_addressable_store cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_3d_image_writes cl_khr_fp64 cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp64


  Platform Name:                                 NVIDIA CUDA
Number of devices:                               1
  Device Type:                                   CL_DEVICE_TYPE_GPU
  Vendor ID:                                     10deh
  Max compute units:                             10
  Max work items dimensions:                     3
    Max work items[0]:                           1024
    Max work items[1]:                           1024
    Max work items[2]:                           64
  Max work group size:                           1024
  Preferred vector width char:                   1
  Preferred vector width short:                  1
  Preferred vector width int:                    1
  Preferred vector width long:                   1
  Preferred vector width float:                  1
  Preferred vector width double:                 1
  Native vector width char:                      1
  Native vector width short:                     1
  Native vector width int:                       1
  Native vector width long:                      1
  Native vector width float:                     1
  Native vector width double:                    1
  Max clock frequency:                           1809Mhz
  Address bits:                                  64
  Max memory allocation:                         1586053120
  Image support:                                 Yes
  Max number of images read arguments:           256
  Max number of images write arguments:          16
  Max image 2D width:                            16384
  Max image 2D height:                           32768
  Max image 3D width:                            16384
  Max image 3D height:                           16384
  Max image 3D depth:                            16384
  Max samplers within kernel:                    32
  Max size of kernel argument:                   4352
  Alignment (bits) of base address:              4096
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     Yes
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               Yes
    Round to +ve and infinity:                   Yes
    IEEE754-2008 fused multiply-add:             Yes
  Cache type:                                    Read/Write
  Cache line size:                               128
  Cache size:                                    491520
  Global memory size:                            6344212480
  Constant buffer size:                          65536
  Max number of constant args:                   9
  Local memory type:                             Scratchpad
  Local memory size:                             49152
  Max pipe arguments:                            0
  Max pipe active reservations:                  0
  Max pipe packet size:                          0
  Max global variable size:                      0
  Max global variable preferred total size:      0
  Max read/write image args:                     0
  Max on device events:                          0
  Queue on device max size:                      0
  Max on device queues:                          0
  Queue on device preferred size:                0
  SVM capabilities:                              
    Coarse grain buffer:                         Yes
    Fine grain buffer:                           No
    Fine grain system:                           No
    Atomics:                                     No
  Preferred platform atomic alignment:           0
  Preferred global atomic alignment:             0
  Preferred local atomic alignment:              0
  Kernel Preferred work group size multiple:     32
  Error correction support:                      0
  Unified memory for Host and Device:            0
  Profiling timer resolution:                    1000
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:                                
    Execute OpenCL kernels:                      Yes
    Execute native function:                     No
  Queue on Host properties:                              
    Out-of-Order:                                Yes
    Profiling :                                  Yes
  Queue on Device properties:                            
    Out-of-Order:                                No
    Profiling :                                  No
  Platform ID:                                   0x59b5a6ffd670
  Name:                                          NVIDIA GeForce GTX 1060 6GB
  Vendor:                                        NVIDIA Corporation
  Device OpenCL C version:                       OpenCL C 1.2 
  Driver version:                                545.23.08
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 3.0 CUDA
  Extensions:                                    cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_device_uuid cl_khr_pci_bus_info cl_khr_external_semaphore cl_khr_external_memory cl_khr_external_semaphore_opaque_fd cl_khr_external_memory_opaque_fd

```

**Comment by SamGinzburg** [comment]
Hi James,

Thanks for checking out VectorVisor! It looks like you're trying to run with POCL---I've had mixed results with that configuration myself. It's probably possible to get it working, but if possible can you try uninstalling POCL and using the default NVIDIA OpenCL libs+icd loader?

Thanks,
Sam

**Comment by JamesYen220** [comment]
Yeah, the issue was that I had two platforms, so the program picked up the CPU instead of the GPU.
